Add set
latedude2/P3_programming-server pull request #4
Opened 2019-10-18 13:47 UTC by abadabada

Adding set to avoid repetition of words.
Adding all words from the wordsList[] to wordsListSet<>
Adding random 25 words from wordsListSet<>to wordsToDisplay[]

2019-10-19 10:35 UTC, latedude2 requested changes

2019-10-19 10:35 UTC, latedude2 commented on .vscode/launch.json
> +{
This whole file should be added to gitignore as it is API specific

2019-10-19 10:35 UTC, latedude2 commented on src/server/WordGenerator.java
>  public class WordGenerator{
I think this class should be static as it has no constructor and is never initialised.

2019-10-19 10:35 UTC, latedude2 commented on src/server/WordGenerator.java
> +                    wordsToDisplay[j] = wordListSet.toArray(new String[wordListSet.size()])[item];
Fix tabbing on this line pls. Also, you can replace wordListSet.size() with size here.

2019-10-19 12:12 UTC, abadabada commented on .vscode/launch.json
> +{
it is in gitignore already idk why it is doing this.

2019-10-19 12:24 UTC, abadabada commented on src/server/WordGenerator.java
>  public class WordGenerator{
Making a class classic means it should be another class, does that mean I have to move it to main and creat a static one there?

2019-10-20 09:49 UTC, latedude2 approved these changes

2019-10-30 08:12 UTC, merged